// RM-side DPI functions for partition: rp_dummy
// Generated by partial_reconfiguration

#include "dpi_shm_channel.h"
#include <svdpi.h>

// Channel base from rm_driver_*.cpp
extern void* g_channel_base;
extern ShmPartitionHeader* g_channel_header;

extern "C" {

void dpi_rm_rp_dummy_data_out_send(int data) {
    ShmPort* p = shm_from_rm_outbox(g_channel_base, g_channel_header->num_to_rm, 0);
    p->data = static_cast<uint64_t>(data);
    p->valid = 1;
}

} // extern "C"