// Static-side DPI functions for partition: rp_dummy
// Generated by partial_reconfiguration

#include "dpi_shm_channel.h"
#include <svdpi.h>

// Partition base from static_driver.cpp
extern void* g_partition_bases[];

extern "C" {

int dpi_static_rp_dummy_data_out_recv_data() {
    return static_cast<int>(shm_from_rm_inbox(g_partition_bases[0], 0, 0)->data);
}

int dpi_static_rp_dummy_data_out_recv_valid() {
    return shm_from_rm_inbox(g_partition_bases[0], 0, 0)->valid ? 1 : 0;
}

} // extern "C"