`timescale 1ns/1ps

module static_region (
    input wire clk,

    output reg [31:0] activity_counter,
    output reg [31:0] computed_result,
    output wire [31:0] rp0_counter,

    // Outputs from echo partition (for cycle accuracy testing)
    output wire [31:0] rm_counter_out,
    output wire [31:0] static_counter_echo_out,
    output wire [31:0] latency_measurement_out
);
    reg  [31:0] operand_a;      // Generated by static, sent TO RM
    reg  [31:0] operand_b;      // Generated by static, sent TO RM
    wire [31:0] result;         // Computed by RM, returned to static
    always @(posedge clk) begin
        activity_counter <= activity_counter + 1;
    end
    always @(posedge clk) begin
        operand_a <= {16'b0, activity_counter[15:0]};   // Lower 16 bits
        operand_b <= {16'b0, activity_counter[31:16]};  // Upper 16 bits
    end
    always @(posedge clk) begin
        computed_result <= result;
    end

    // ========================================================================
    // Partition rp0: counter_rm (or passthrough_rm)
    // Replaced by DPI bridge during simulation
    // ========================================================================
    counter_rm u_counter_rm (
        .clk(clk),
        .counter(rp0_counter)
    );
    // ========================================================================
    // Partition rp1: adder_rm (or subtractor_rm, cipher RMs)
    // This instantiation is replaced by a DPI bridge during simulation
    // ========================================================================
    adder_rm u_adder_rm (
        .clk(clk),
        .operand_a(operand_a),    // INTERNAL signal → RM
        .operand_b(operand_b),    // INTERNAL signal → RM
        .result(result)           // RM → INTERNAL signal
    );

    // ========================================================================
    // Partition rp_echo: echo_counter_rm
    // This partition tests cycle accuracy by correlating counters between
    // static region and RM. The activity_counter is sent to the RM, which
    // echoes it back and compares with its own internal counter.
    // ========================================================================
    echo_counter_rm u_echo_counter_rm (
        .clk(clk),
        .static_counter_in(activity_counter),           // Send our counter TO RM
        .rm_counter(rm_counter_out),                    // Receive RM's counter
        .static_counter_echo(static_counter_echo_out),  // Receive echo of what we sent
        .latency_measurement(latency_measurement_out)   // RM's latency calculation
    );

endmodule
