`timescale 1ns/1ps

module static_region (
    input wire clk,

    output reg [31:0] activity_counter,
    output reg [31:0] computed_result,
    output wire [31:0] rp0_counter
);
    reg  [31:0] operand_a;      // Generated by static, sent TO RM
    reg  [31:0] operand_b;      // Generated by static, sent TO RM
    wire [31:0] result;         // Computed by RM, returned to static
    always @(posedge clk) begin
        activity_counter <= activity_counter + 1;
    end
    always @(posedge clk) begin
        operand_a <= {16'b0, activity_counter[15:0]};   // Lower 16 bits
        operand_b <= {16'b0, activity_counter[31:16]};  // Upper 16 bits
    end
    always @(posedge clk) begin
        computed_result <= result;
    end

    // ========================================================================
    // Partition rp0: counter_rm (or passthrough_rm)
    // is replaced by a bridge for switchboard
    // ========================================================================
    counter_rm u_counter_rm (
        .clk(clk),
        .counter(rp0_counter)
    );
    // ========================================================================
    // Partition rp1: adder_rm (or subtractor_rm, cipher RMs)
    // This instantiation will be REPLACED by a queue bridge during simulation
    // ========================================================================
    adder_rm u_adder_rm (
        .clk(clk),
        .operand_a(operand_a),    // INTERNAL signal → RM
        .operand_b(operand_b),    // INTERNAL signal → RM
        .result(result)           // RM → INTERNAL signal
    );

endmodule
