// Static-side DPI bridge for partition: rp_wide64
// Replaces wide64_rm in static region
// Generated by partial_reconfiguration DPI bridge generator

`timescale 1ns/1ps

module wide64_rm (
    input wire clk,
    input wire [47:0] wide_in,
    input wire [63:0] full64_in,
    output reg [47:0] wide_out,
    output reg [63:0] full64_out
);

    import "DPI-C" function void dpi_static_rp_wide64_wide_in_send(input longint data);
    import "DPI-C" function void dpi_static_rp_wide64_full64_in_send(input longint data);

    import "DPI-C" function longint dpi_static_rp_wide64_wide_out_recv_data();
    import "DPI-C" function int dpi_static_rp_wide64_wide_out_recv_valid();
    import "DPI-C" function longint dpi_static_rp_wide64_full64_out_recv_data();
    import "DPI-C" function int dpi_static_rp_wide64_full64_out_recv_valid();

    // Send inputs to RM via DPI channels
    always @(posedge clk) begin
        dpi_static_rp_wide64_wide_in_send(longint'({16'd0, wide_in}));
        dpi_static_rp_wide64_full64_in_send(full64_in);
    end

    // Receive outputs from RM via DPI channels
    always @(posedge clk) begin
        if (dpi_static_rp_wide64_wide_out_recv_valid())
            wide_out <= dpi_static_rp_wide64_wide_out_recv_data()[47:0];
        if (dpi_static_rp_wide64_full64_out_recv_valid())
            full64_out <= dpi_static_rp_wide64_full64_out_recv_data();
    end

endmodule