"""
Cocotb Integration Code Generator.

Generates files needed for cocotb to host the static region while RM binaries
run as separate processes communicating via shared memory and barriers:

1. pr_cocotb_top.sv — Wrapper module that cocotb sees as DUT. Contains a
   negedge DPI barrier call and instantiates the user's static region.

2. pr_cocotb_barrier.cpp — DPI C++ library (no main()). Implements the
   collapsed 3-phase barrier protocol in a single negedge DPI call,
   plus swap_channels() and process_commands().
"""
from typing import List, Dict, Any
from pathlib import Path
import logging

from .dpi_cpp_generator import PartitionInfo, StaticInfo, _num_chunks, _total_slots, _slot_offsets

logger = logging.getLogger(__name__)


class CocotbGenerator:
    """Generates cocotb integration files for the PR simulation."""

    def __init__(self, build_dir: str):
        self.build_dir = Path(build_dir)
        self.dpi_dir = self.build_dir / 'dpi'
        self.bridges_dir = self.build_dir / 'bridges'
        self.dpi_dir.mkdir(parents=True, exist_ok=True)
        self.bridges_dir.mkdir(parents=True, exist_ok=True)

    def generate_all(
        self,
        partitions: List[PartitionInfo],
        static_info: StaticInfo,
    ) -> Dict[str, Path]:
        """Generate all cocotb integration files.

        Returns
        -------
        dict
            {'top_sv': Path, 'barrier_cpp': Path}
        """
        top_sv = self.generate_cocotb_top_sv(partitions, static_info)
        barrier_cpp = self.generate_cocotb_barrier_cpp(partitions, static_info)
        return {
            'top_sv': top_sv,
            'barrier_cpp': barrier_cpp,
        }

    # ── pr_cocotb_top.sv ──────────────────────────────────────────────

    def generate_cocotb_top_sv(
        self,
        partitions: List[PartitionInfo],
        static_info: StaticInfo,
    ) -> Path:
        """Generate the cocotb top-level wrapper SystemVerilog module.

        This module:
        - Is the DUT that cocotb drives (clock, reset, user ports)
        - Contains an always @(negedge clk) block that calls the barrier DPI
        - Instantiates the user's static region, wiring all ports through
        """
        lines = []
        lines.append("`timescale 1ns/1ps")
        lines.append("")
        lines.append("// Generated by partial_reconfiguration — cocotb top-level wrapper")
        lines.append("// Do not edit — regenerated on each build")
        lines.append("")

        # Module declaration — expose all user-visible ports
        clk = static_info.clock_name
        rst = static_info.reset_name
        port_lines = [f"    input wire {clk}"]
        if rst:
            port_lines.append(f"    input wire {rst}")
        for port in static_info.ports:
            direction = 'input' if port['direction'] == 'input' else 'output'
            w = port.get('width', 1)
            name = port['name']
            if name == clk or name == rst:
                continue  # already declared
            if w > 1:
                port_lines.append(f"    {direction} wire [{w-1}:0] {name}")
            else:
                port_lines.append(f"    {direction} wire {name}")

        lines.append("module pr_cocotb_top (")
        lines.append(",\n".join(port_lines))
        lines.append(");")
        lines.append("")

        # DPI import for negedge barrier
        lines.append('    import "DPI-C" function void pr_cocotb_negedge_barrier();')
        lines.append("")
        lines.append(f"    always @(negedge {clk}) begin")
        lines.append("        pr_cocotb_negedge_barrier();")
        lines.append("    end")
        lines.append("")

        # Instantiate user's static region
        lines.append(f"    // Instantiate user static region")
        inst_ports = []
        inst_ports.append(f"        .{clk}({clk})")
        if rst:
            inst_ports.append(f"        .{rst}({rst})")
        for port in static_info.ports:
            name = port['name']
            if name == clk or name == rst:
                continue
            inst_ports.append(f"        .{name}({name})")

        lines.append(f"    {static_info.design_name} static_inst (")
        lines.append(",\n".join(inst_ports))
        lines.append("    );")
        lines.append("")
        lines.append("endmodule")
        lines.append("")

        path = self.bridges_dir / "pr_cocotb_top.sv"
        path.write_text("\n".join(lines))
        logger.info(f"Generated: {path}")
        return path

    # ── pr_cocotb_barrier.cpp ─────────────────────────────────────────

    def generate_cocotb_barrier_cpp(
        self,
        partitions: List[PartitionInfo],
        static_info: StaticInfo,
    ) -> Path:
        """Generate the cocotb barrier DPI C++ file (no main()).

        This file:
        - Defines g_partition_bases[] (extern'd by dpi_static_*.cpp)
        - Implements pr_cocotb_negedge_barrier() with collapsed 3-phase barrier
        - Uses __attribute__((constructor)) for SHM initialization
        - Implements swap_channels() and process_commands() (same logic as static_driver.cpp)
        """
        num_parts = len(partitions)
        lines = []
        lines.append("// Cocotb barrier DPI library — generated by partial_reconfiguration")
        lines.append("// No main() — cocotb provides main via verilator.cpp")
        lines.append("")
        lines.append('#include "dpi_shm_channel.h"')
        lines.append('#include "barrier_sync.h"')
        lines.append('#include "shm_mailbox.h"')
        lines.append("")
        lines.append("#include <cstdint>")
        lines.append("#include <cstring>")
        lines.append("#include <cstdlib>")
        lines.append("#include <iostream>")
        lines.append("#include <sys/mman.h>")
        lines.append("#include <sys/stat.h>")
        lines.append("#include <fcntl.h>")
        lines.append("#include <unistd.h>")
        lines.append("#include <sched.h>")
        lines.append("")

        # Globals
        lines.append(f"#define NUM_PARTITIONS {num_parts}")
        lines.append("")
        lines.append("// Exported for dpi_static_*.cpp")
        lines.append("void* g_partition_bases[NUM_PARTITIONS];")

        # Inline partition port accessors (replaces signal_access.h without Vstatic_region.h dep)
        lines.append("")
        lines.append("// Partition port accessors (no static model dependency)")
        for part in partitions:
            num_to_rm_slots = _total_slots(part.to_rm_ports)

            lines.append(f"static inline uint64_t read_{part.name}_port(int port_idx) {{")
            lines.append(f"    void* base = g_partition_bases[{part.index}];")
            lines.append(f"    ShmPartitionHeader* hdr = shm_header(base);")
            lines.append("    switch (port_idx) {")
            slot_idx = 0
            for port in part.to_rm_ports:
                nc = _num_chunks(port.get('width', 32))
                for _ in range(nc):
                    lines.append(f"        case {slot_idx}: {{")
                    lines.append(f"            ShmPortOverride* ovr = shm_to_rm_override(base, {slot_idx});")
                    lines.append(f"            if (shm_load32(&ovr->active)) return shm_load64_relaxed(&ovr->value);")
                    lines.append(f"            return shm_load64_relaxed(&shm_to_rm_inbox(base, {slot_idx})->data);")
                    lines.append(f"        }}")
                    slot_idx += 1
            from_slot_idx = 0
            for port in part.from_rm_ports:
                nc = _num_chunks(port.get('width', 32))
                for _ in range(nc):
                    lines.append(f"        case {slot_idx}: return shm_load64_relaxed(&shm_from_rm_outbox(base, hdr->num_to_rm, {from_slot_idx})->data);")
                    slot_idx += 1
                    from_slot_idx += 1
            lines.append("        default: return 0;")
            lines.append("    }")
            lines.append("}")
            lines.append("")

            lines.append(f"static inline void write_{part.name}_port(int port_idx, uint64_t value) {{")
            lines.append(f"    void* base = g_partition_bases[{part.index}];")
            lines.append("    switch (port_idx) {")
            slot_idx = 0
            for port in part.to_rm_ports:
                nc = _num_chunks(port.get('width', 32))
                for _ in range(nc):
                    lines.append(f"        case {slot_idx}: {{")
                    lines.append(f"            ShmPortOverride* ovr = shm_to_rm_override(base, {slot_idx});")
                    lines.append(f"            shm_store64_relaxed(&ovr->value, value);")
                    lines.append(f"            shm_store32(&ovr->active, 1);")
                    lines.append(f"            break;")
                    lines.append(f"        }}")
                    slot_idx += 1
            lines.append("        default: break;")
            lines.append("    }")
            lines.append("}")
            lines.append("")
        lines.append("static ShmPartitionHeader* g_partition_headers[NUM_PARTITIONS];")
        lines.append("static size_t g_partition_sizes[NUM_PARTITIONS];")
        lines.append("")
        lines.append("static ShmMailbox* g_mailbox = nullptr;")
        lines.append("static ShmBarrier* g_barrier = nullptr;")
        lines.append("static uint32_t g_local_sense = 0;")
        lines.append("static bool g_first_cycle = true;")
        lines.append("static bool g_quit = false;")
        lines.append("static int g_reconfig_partition = -1;")
        lines.append("")

        # mmap helper
        lines.append("static void* mmap_file(const char* path, size_t expected_size) {")
        lines.append("    int fd = open(path, O_RDWR);")
        lines.append("    if (fd < 0) { perror(path); return nullptr; }")
        lines.append("    struct stat st;")
        lines.append("    fstat(fd, &st);")
        lines.append("    size_t sz = (expected_size > 0) ? expected_size : (size_t)st.st_size;")
        lines.append("    void* ptr = mmap(nullptr, sz, PROT_READ | PROT_WRITE, MAP_SHARED, fd, 0);")
        lines.append("    if (ptr == MAP_FAILED) { perror(\"mmap\"); close(fd); return nullptr; }")
        lines.append("    // Keep fd open (mmap stays valid)")
        lines.append("    return ptr;")
        lines.append("}")
        lines.append("")

        # swap_channels — identical to static_driver.cpp
        lines.append("static void swap_channels() {")
        lines.append("    for (int p = 0; p < NUM_PARTITIONS; p++) {")
        lines.append("        void* base = g_partition_bases[p];")
        lines.append("        ShmPartitionHeader* hdr = g_partition_headers[p];")
        lines.append("        if (shm_load32(&hdr->quit)) continue;  // skip partitions being reconfigured")
        lines.append("        uint32_t T = hdr->num_to_rm;")
        lines.append("        uint32_t F = hdr->num_from_rm;")
        lines.append("        for (uint32_t i = 0; i < T; i++) {")
        lines.append("            ShmPort* ob = shm_to_rm_outbox(base, i);")
        lines.append("            ShmPort* ib = shm_to_rm_inbox(base, i);")
        lines.append("            ib->data = ob->data;")
        lines.append("            ib->valid = ob->valid;")
        lines.append("            ob->valid = 0;")
        lines.append("        }")
        lines.append("        for (uint32_t i = 0; i < F; i++) {")
        lines.append("            ShmPort* ob = shm_from_rm_outbox(base, T, i);")
        lines.append("            ShmPort* ib = shm_from_rm_inbox(base, T, i);")
        lines.append("            ib->data = ob->data;")
        lines.append("            ib->valid = ob->valid;")
        lines.append("            ob->valid = 0;")
        lines.append("        }")
        lines.append("    }")
        lines.append("}")
        lines.append("")

        # process_commands — same logic as static_driver.cpp
        # Note: in cocotb mode, read_static_port/write_static_port are not available
        # since cocotb drives the static model directly via VPI. Only partition
        # reads/writes via SHM are supported through the mailbox.
        lines.append("static void process_commands() {")
        lines.append("    if (g_mailbox->cmd == CMD_NOOP) return;")
        lines.append("")
        lines.append("    switch (g_mailbox->cmd) {")

        # CMD_READ
        lines.append("    case CMD_READ: {")
        lines.append("        uint64_t val = 0;")
        # No static port access in cocotb mode — cocotb reads static ports via VPI
        lines.append("        if (g_mailbox->target == TARGET_STATIC) {")
        lines.append("            // Static port reads not supported via mailbox in cocotb mode.")
        lines.append("            // Use cocotb VPI to read static region ports directly.")
        lines.append("            val = 0;")
        lines.append("        }")
        for part in partitions:
            lines.append(f"        else if (g_mailbox->target == {part.index + 1}) {{")
            lines.append(f"            val = read_{part.name}_port(g_mailbox->port_idx);")
            lines.append(f"        }}")
        lines.append("        g_mailbox->read_value = val;")
        lines.append("        g_mailbox->cmd = CMD_NOOP;")
        lines.append("        break;")
        lines.append("    }")

        # CMD_WRITE
        lines.append("    case CMD_WRITE: {")
        lines.append("        if (g_mailbox->target == TARGET_STATIC) {")
        lines.append("            // Static port writes not supported via mailbox in cocotb mode.")
        lines.append("        }")
        for part in partitions:
            lines.append(f"        else if (g_mailbox->target == {part.index + 1}) {{")
            lines.append(f"            write_{part.name}_port(g_mailbox->port_idx, g_mailbox->write_value);")
            lines.append(f"        }}")
        lines.append("        g_mailbox->cmd = CMD_NOOP;")
        lines.append("        break;")
        lines.append("    }")

        # CMD_RECONFIG
        lines.append("    case CMD_RECONFIG: {")
        lines.append("        int part_id = g_mailbox->target - 1;")
        lines.append("        if (part_id >= 0 && part_id < NUM_PARTITIONS) {")
        lines.append("            // Set quit flag — RM will exit after current cycle")
        lines.append("            shm_store32(&g_partition_headers[part_id]->quit, 1);")
        lines.append("            // Clear overrides")
        lines.append("            void* base = g_partition_bases[part_id];")
        lines.append("            for (uint32_t i = 0; i < g_partition_headers[part_id]->num_to_rm; i++) {")
        lines.append("                ShmPortOverride* ovr = shm_to_rm_override(base, i);")
        lines.append("                shm_store32(&ovr->active, 0);")
        lines.append("            }")
        lines.append("            g_reconfig_partition = part_id;")
        lines.append("        }")
        lines.append("        // Don't set cmd=NOOP yet — Python waits until reconfig completes")
        lines.append("        break;")
        lines.append("    }")

        # CMD_BATCH
        lines.append("    case CMD_BATCH: {")
        lines.append("        uint32_t n = g_mailbox->batch_count;")
        lines.append("        if (n > MAX_BATCH) n = MAX_BATCH;")
        lines.append("        for (uint32_t b = 0; b < n; b++) {")
        lines.append("            ShmBatchSlot* slot = &g_mailbox->batch[b];")
        lines.append("            switch (slot->cmd) {")
        lines.append("            case CMD_READ: {")
        lines.append("                uint64_t val = 0;")
        lines.append("                if (slot->target == TARGET_STATIC) { val = 0; }")
        for part in partitions:
            lines.append(f"                else if (slot->target == {part.index + 1}) {{")
            lines.append(f"                    val = read_{part.name}_port(slot->port_idx);")
            lines.append(f"                }}")
        lines.append("                slot->read_value = val;")
        lines.append("                break;")
        lines.append("            }")
        lines.append("            case CMD_WRITE: {")
        lines.append("                if (slot->target == TARGET_STATIC) { /* noop in cocotb mode */ }")
        for part in partitions:
            lines.append(f"                else if (slot->target == {part.index + 1}) {{")
            lines.append(f"                    write_{part.name}_port(slot->port_idx, slot->write_value);")
            lines.append(f"                }}")
        lines.append("                break;")
        lines.append("            }")
        lines.append("            }")
        lines.append("        }")
        lines.append("        g_mailbox->cmd = CMD_NOOP;")
        lines.append("        break;")
        lines.append("    }")

        # CMD_QUIT
        lines.append("    case CMD_QUIT:")
        lines.append("        g_quit = true;")
        lines.append("        g_mailbox->cmd = CMD_NOOP;")
        lines.append("        break;")
        lines.append("    }")
        lines.append("}")
        lines.append("")

        # The main negedge DPI function — collapsed 3-phase barrier
        lines.append('extern "C" {')
        lines.append("")
        lines.append("void pr_cocotb_negedge_barrier() {")
        lines.append("    if (!g_mailbox || !g_barrier) return;  // SHM init failed")
        lines.append("    if (g_quit) return;")
        lines.append("")
        lines.append("    if (!g_first_cycle) {")
        lines.append("        // B3: posedge done (previous cycle's posedge just completed)")
        lines.append("        barrier_wait(g_barrier, &g_local_sense);")
        lines.append("")
        lines.append("        // Handle pending reconfiguration after B3")
        lines.append("        // After B3: old RM will check quit and exit. We must SPIN here")
        lines.append("        // (mirroring static_driver.cpp) until the new RM sets rm_ready=1.")
        lines.append("        // This keeps the B1 participant count correct: we don't call B1")
        lines.append("        // until the new RM has joined, so B1 always has num_processes takers.")
        lines.append("        if (g_reconfig_partition >= 0) {")
        lines.append("            ShmPartitionHeader* hdr = g_partition_headers[g_reconfig_partition];")
        lines.append("            // Phase 1: wait for old RM to clear rm_ready (it clears on quit) or parent to clear it")
        lines.append("            while (shm_load32(&hdr->rm_ready)) { sched_yield(); }")
        lines.append("            // Phase 2: wait for new RM to set rm_ready (started by parent after old RM exits)")
        lines.append("            while (!shm_load32(&hdr->rm_ready)) { sched_yield(); }")
        lines.append("            shm_store32(&hdr->quit, 0);")
        lines.append("            shm_store32(&hdr->rm_ready, 0);")
        lines.append("            g_reconfig_partition = -1;")
        lines.append("            g_mailbox->cmd = CMD_NOOP;  // Signal completion to Python")
        lines.append("        }")
        lines.append("    }")
        lines.append("    g_first_cycle = false;")
        lines.append("")
        lines.append("    // B1: negedge done")
        lines.append("    barrier_wait(g_barrier, &g_local_sense);")
        lines.append("")
        lines.append("    // B2: swap channels + process commands")
        lines.append("    swap_channels();")
        lines.append("    process_commands();")
        lines.append("    if (g_mailbox->cmd == CMD_QUIT) { g_quit = true; }")
        lines.append("    barrier_wait(g_barrier, &g_local_sense);")
        lines.append("")
        lines.append("    // After B2: cocotb proceeds to posedge eval.")
        lines.append("    // DPI bridge always @(posedge clk) blocks fire during that eval.")
        lines.append("    g_mailbox->cycle_count++;")
        lines.append("}")
        lines.append("")
        lines.append("} // extern \"C\"")
        lines.append("")

        # Constructor: init SHM from environment variable
        lines.append("// GCC/Clang constructor — runs before cocotb's VPI init")
        lines.append("__attribute__((constructor))")
        lines.append("static void pr_cocotb_init() {")
        lines.append('    const char* shm_dir = std::getenv("PR_SHM_DIR");')
        lines.append("    if (!shm_dir) {")
        lines.append('        std::cerr << "PR_SHM_DIR not set — PR barrier disabled" << std::endl;')
        lines.append("        return;")
        lines.append("    }")
        lines.append("    std::string dir(shm_dir);")
        lines.append("")
        lines.append("    // Open mailbox")
        lines.append('    g_mailbox = (ShmMailbox*)mmap_file((dir + "/cmd_mailbox.shm").c_str(), SHM_MAILBOX_SIZE);')
        lines.append("    if (!g_mailbox) return;")
        lines.append("")
        lines.append("    // Open barrier")
        lines.append('    g_barrier = (ShmBarrier*)mmap_file((dir + "/barrier.shm").c_str(), 4096);')
        lines.append("    if (!g_barrier) return;")
        lines.append("")
        lines.append("    // Open partition channels")
        lines.append("    for (int p = 0; p < NUM_PARTITIONS; p++) {")
        lines.append('        std::string path = dir + "/partition_" + std::to_string(p) + ".shm";')
        lines.append("        g_partition_bases[p] = mmap_file(path.c_str(), 0);")
        lines.append("        if (!g_partition_bases[p]) return;")
        lines.append("        g_partition_headers[p] = shm_header(g_partition_bases[p]);")
        lines.append("    }")
        lines.append("")
        lines.append("    // Init barrier sense")
        lines.append("    g_local_sense = __atomic_load_n(&g_barrier->sense, __ATOMIC_ACQUIRE);")
        lines.append("")
        lines.append("    // Signal ready")
        lines.append("    g_mailbox->sim_status = SIM_STATUS_RUNNING;")
        lines.append("    g_mailbox->cycle_count = 0;")
        lines.append("}")
        lines.append("")

        path = self.dpi_dir / "pr_cocotb_barrier.cpp"
        path.write_text("\n".join(lines))
        logger.info(f"Generated: {path}")
        return path
