"""
DPI Bridge Generator for partition boundaries.

Generates two SystemVerilog modules per partition:
1. Static-side DPI bridge: Same port signature as the RM (drop-in replacement
   in the static region). Uses DPI-C function calls to read/write shared memory.
2. RM-side DPI wrapper: Wraps real RM with DPI channel I/O.

Width-aware: DPI types are selected based on actual port widths to avoid
Verilator WIDTHEXPAND/WIDTHTRUNC warnings. Ports are classified into
DPI type bands:
  - 1-32 bits  -> DPI `int`     (C++ `int`)
  - 33-64 bits -> DPI `longint` (C++ `long long`)
"""
from typing import List, Dict
from pathlib import Path
from dataclasses import dataclass
import logging

logger = logging.getLogger(__name__)


@dataclass
class BoundaryPort:
    """A port on the partition boundary."""
    name: str
    width: int
    direction: str  # 'to_rm' or 'from_rm'


@dataclass
class PartitionBoundaryDef:
    """Definition of a partition boundary for DPI bridge generation."""
    partition_name: str
    rm_module_name: str
    ports: List[BoundaryPort]
    clock_name: str = 'clk'


def _dpi_type(width: int) -> str:
    """Select the DPI-C type that covers the given bit width."""
    if width <= 32:
        return 'int'
    elif width <= 64:
        return 'longint'
    else:
        raise ValueError(
            f"Port width {width} exceeds 64 bits — "
            f"DPI-C scalar types max out at longint (64). "
            f"Consider splitting into multiple ports."
        )


def _sv_send_cast(port: BoundaryPort) -> str:
    """
    Generate the SV expression that widens a port value to the DPI type width.

    For exact-width matches (32 or 64), no cast needed.
    For narrower signals, zero-extend to the DPI type width.
    """
    dpi = _dpi_type(port.width)
    if dpi == 'int':
        if port.width == 32:
            return port.name
        # Zero-extend narrow signal to 32 bits
        return f"int'({{{32 - port.width}'d0, {port.name}}})"
    else:  # longint
        if port.width == 64:
            return port.name
        return f"longint'({{{64 - port.width}'d0, {port.name}}})"


def _sv_recv_trunc(port: BoundaryPort, expr: str) -> str:
    """
    Generate the SV expression that truncates a DPI return value to port width.

    For exact-width matches, direct assignment.
    For narrower ports, bit-select the relevant bits.
    """
    dpi = _dpi_type(port.width)
    if dpi == 'int' and port.width == 32:
        return expr
    if dpi == 'longint' and port.width == 64:
        return expr
    return f"{expr}[{port.width - 1}:0]"


class DpiBridgeGenerator:
    """
    Generates DPI-based bridge modules for partition boundaries.

    For each partition, generates:
    1. Static-side bridge: same module name as RM, uses DPI-C send/recv
    2. RM-side DPI wrapper: wraps real RM, uses DPI-C send/recv

    All DPI function signatures use width-appropriate types selected by
    _dpi_type() to avoid Verilator width warnings.
    """

    def __init__(self, build_dir: str = None):
        self.build_dir = Path(build_dir) if build_dir else Path('build/pr')
        self.bridges_dir = self.build_dir / 'bridges'
        self.wrappers_dir = self.build_dir / 'wrappers'
        self.bridges_dir.mkdir(parents=True, exist_ok=True)
        self.wrappers_dir.mkdir(parents=True, exist_ok=True)

    def generate_static_side_bridge(self, boundary: PartitionBoundaryDef) -> Path:
        """
        Generate the static-side DPI bridge.

        This module has the same name and ports as the RM, so it acts as a
        drop-in replacement in the static region. Instead of real logic,
        it uses DPI-C functions to send inputs to and receive outputs from
        the RM running in another process.
        """
        part = boundary.partition_name
        module_name = boundary.rm_module_name
        to_rm = [p for p in boundary.ports if p.direction == 'to_rm']
        from_rm = [p for p in boundary.ports if p.direction == 'from_rm']

        lines = []
        lines.append(f"// Static-side DPI bridge for partition: {part}")
        lines.append(f"// Replaces {module_name} in static region")
        lines.append("// Generated by partial_reconfiguration DPI bridge generator")
        lines.append("")
        lines.append("`timescale 1ns/1ps")
        lines.append("")

        # Module declaration with same ports as RM
        lines.append(f"module {module_name} (")
        lines.append(f"    input wire {boundary.clock_name},")
        port_lines = []
        for port in boundary.ports:
            width_str = f"[{port.width-1}:0] " if port.width > 1 else ""
            if port.direction == 'to_rm':
                port_lines.append(f"    input wire {width_str}{port.name}")
            else:
                port_lines.append(f"    output reg {width_str}{port.name}")
        lines.append(",\n".join(port_lines))
        lines.append(");")
        lines.append("")

        # DPI imports — width-matched types
        for port in to_rm:
            dt = _dpi_type(port.width)
            lines.append(
                f'    import "DPI-C" function void '
                f'dpi_static_{part}_{port.name}_send(input {dt} data);'
            )
        lines.append("")

        for port in from_rm:
            dt = _dpi_type(port.width)
            lines.append(
                f'    import "DPI-C" function {dt} '
                f'dpi_static_{part}_{port.name}_recv_data();'
            )
            lines.append(
                f'    import "DPI-C" function int '
                f'dpi_static_{part}_{port.name}_recv_valid();'
            )
        lines.append("")

        # Send inputs to RM every cycle
        if to_rm:
            lines.append(f"    // Send inputs to RM via DPI channels")
            lines.append(f"    always @(posedge {boundary.clock_name}) begin")
            for port in to_rm:
                arg = _sv_send_cast(port)
                lines.append(f"        dpi_static_{part}_{port.name}_send({arg});")
            lines.append("    end")
            lines.append("")

        # Receive outputs from RM every cycle
        if from_rm:
            lines.append(f"    // Receive outputs from RM via DPI channels")
            lines.append(f"    always @(posedge {boundary.clock_name}) begin")
            for port in from_rm:
                recv_fn = f"dpi_static_{part}_{port.name}_recv_data()"
                trunc_expr = _sv_recv_trunc(port, recv_fn)
                lines.append(f"        if (dpi_static_{part}_{port.name}_recv_valid())")
                lines.append(f"            {port.name} <= {trunc_expr};")
            lines.append("    end")
            lines.append("")

        lines.append("endmodule")

        output_path = self.bridges_dir / f"{module_name}.sv"
        output_path.write_text("\n".join(lines))
        logger.info(f"Generated static-side DPI bridge: {output_path}")
        return output_path

    def generate_rm_side_wrapper(
        self,
        boundary: PartitionBoundaryDef,
        rm_design_name: str,
    ) -> Path:
        """
        Generate the RM-side DPI wrapper.

        This module wraps the real RM, connecting its ports to DPI channels.
        Input ports are driven by data received from the static region via DPI.
        Output ports are sent to the static region via DPI.

        Internal signals use `/* verilator public */` annotation for direct
        C++ access (Python signal reads/writes).
        """
        part = boundary.partition_name
        to_rm = [p for p in boundary.ports if p.direction == 'to_rm']
        from_rm = [p for p in boundary.ports if p.direction == 'from_rm']
        wrapper_name = f"{rm_design_name}_dpi_wrapper"

        lines = []
        lines.append(f"// RM-side DPI wrapper for {rm_design_name}")
        lines.append(f"// Partition: {part}")
        lines.append("// Generated by partial_reconfiguration DPI bridge generator")
        lines.append("")
        lines.append("`timescale 1ns/1ps")
        lines.append("")

        # Module declaration - only clk as port
        lines.append(f"module {wrapper_name} (")
        lines.append(f"    input wire clk")
        lines.append(");")
        lines.append("")

        # DPI imports — width-matched types
        for port in to_rm:
            dt = _dpi_type(port.width)
            lines.append(
                f'    import "DPI-C" function {dt} '
                f'dpi_rm_{part}_{port.name}_recv_data();'
            )
            lines.append(
                f'    import "DPI-C" function int '
                f'dpi_rm_{part}_{port.name}_recv_valid();'
            )

        for port in from_rm:
            dt = _dpi_type(port.width)
            lines.append(
                f'    import "DPI-C" function void '
                f'dpi_rm_{part}_{port.name}_send(input {dt} data);'
            )
        lines.append("")

        # Internal registers for to_rm ports (inputs to RM)
        for port in to_rm:
            width_str = f"[{port.width-1}:0]" if port.width > 1 else ""
            lines.append(f"    reg {width_str} {port.name} /* verilator public */;")

        # Internal wires for from_rm ports (outputs from RM)
        for port in from_rm:
            width_str = f"[{port.width-1}:0]" if port.width > 1 else ""
            lines.append(f"    wire {width_str} {port.name} /* verilator public */;")
        lines.append("")

        # Instantiate the real RM
        lines.append(f"    // Instantiate the real RM: {rm_design_name}")
        lines.append(f"    {rm_design_name} u_rm (")
        lines.append(f"        .{boundary.clock_name}(clk),")
        port_conns = []
        for port in to_rm:
            port_conns.append(f"        .{port.name}({port.name})")
        for port in from_rm:
            port_conns.append(f"        .{port.name}({port.name})")
        lines.append(",\n".join(port_conns))
        lines.append("    );")
        lines.append("")

        # Update inputs from DPI channels
        if to_rm:
            lines.append(f"    // Update inputs from DPI channels (from static region)")
            lines.append(f"    always @(posedge clk) begin")
            for port in to_rm:
                recv_fn = f"dpi_rm_{part}_{port.name}_recv_data()"
                trunc_expr = _sv_recv_trunc(port, recv_fn)
                lines.append(f"        if (dpi_rm_{part}_{port.name}_recv_valid())")
                lines.append(f"            {port.name} <= {trunc_expr};")
            lines.append("    end")
            lines.append("")

        # Send outputs to static via DPI
        if from_rm:
            lines.append(f"    // Send outputs to static region via DPI channels")
            lines.append(f"    always @(posedge clk) begin")
            for port in from_rm:
                arg = _sv_send_cast(port)
                lines.append(f"        dpi_rm_{part}_{port.name}_send({arg});")
            lines.append("    end")
            lines.append("")

        lines.append("endmodule")

        output_path = self.wrappers_dir / f"{wrapper_name}.sv"
        output_path.write_text("\n".join(lines))
        logger.info(f"Generated RM-side DPI wrapper: {output_path}")
        return output_path

    def generate_both(
        self,
        boundary: PartitionBoundaryDef,
        rm_design_name: str,
    ) -> tuple:
        """Generate both static-side bridge and RM-side wrapper."""
        bridge_path = self.generate_static_side_bridge(boundary)
        wrapper_path = self.generate_rm_side_wrapper(boundary, rm_design_name)
        return bridge_path, wrapper_path
