"""
Makefile Generator for multi-binary DPI-based Verilator simulation.

Generates a Makefile that:
1. Verilates each module separately into .a library archives
2. Compiles DPI C++ sources (separate for static-side and RM-side)
3. Links a static_binary and per-RM rm_binary executables
"""
from typing import List, Dict, Any
from pathlib import Path
from dataclasses import dataclass, field
import logging

logger = logging.getLogger(__name__)


@dataclass
class ModuleBuildInfo:
    """Build info for a single Verilator module."""
    name: str  # Module name (used for obj_dir naming)
    top_module: str  # Top-level module name for verilator
    sources: List[str]  # List of RTL source file paths
    include_dirs: List[str] = field(default_factory=list)
    verilator_flags: List[str] = field(default_factory=list)
    obj_dir_prefix: str = ''  # 'static/', 'rm/counter_rm/', etc.


@dataclass
class RmBinaryInfo:
    """Build info for one RM binary."""
    name: str  # RM variant name (e.g. 'counter_rm')
    module: ModuleBuildInfo  # The RM's Verilator module
    partition_name: str  # Which partition this RM belongs to
    driver_cpp: str  # Path to rm_driver_{name}.cpp
    dpi_rm_cpp: str  # Path to dpi_rm_{partition}.cpp


class MakefileGenerator:
    """Generates Makefile for building multi-binary DPI simulation."""

    def __init__(self, build_dir: str):
        self.build_dir = Path(build_dir)
        self.dpi_dir = self.build_dir / 'dpi'

    def generate(
        self,
        static_module: ModuleBuildInfo,
        rm_binaries: List[RmBinaryInfo],
        static_dpi_cpp_files: List[str],
        static_driver_cpp: str,
        trace: bool = False,
        trace_type: str = 'vcd',
        extra_cflags: str = '',
        extra_ldflags: str = '',
    ) -> Path:
        """Generate the Makefile for multi-binary architecture.

        Parameters
        ----------
        static_module : ModuleBuildInfo
            Build info for the static region module.
        rm_binaries : list of RmBinaryInfo
            Build info for each RM binary.
        static_dpi_cpp_files : list of str
            Paths to static-side DPI C++ source files
            (dpi_static_*.cpp files).
        static_driver_cpp : str
            Path to static_driver.cpp.
        trace : bool
            Enable waveform tracing.
        trace_type : str
            Trace format: 'vcd' or 'fst'.
        extra_cflags : str
            Additional compiler flags.
        extra_ldflags : str
            Additional linker flags.

        Returns
        -------
        Path
            Path to the generated Makefile.
        """
        lines = []
        lines.append("# Generated Makefile for multi-binary DPI Verilator simulation")
        lines.append("# Do not edit - regenerated by partial_reconfiguration")
        lines.append("")

        # Variables
        lines.append(f"BUILD_DIR := {self.build_dir}")
        lines.append(f"DPI_DIR := {self.dpi_dir}")
        lines.append(f"STATIC_BINARY := $(BUILD_DIR)/static_binary")
        lines.append("")

        # RM binary paths
        rm_binary_vars = []
        for rm in rm_binaries:
            var_name = f"RM_BINARY_{rm.name.upper()}"
            lines.append(f"{var_name} := $(BUILD_DIR)/rm/{rm.name}/rm_binary")
            rm_binary_vars.append(f"$({var_name})")
        lines.append("")

        # Find Verilator root
        lines.append("VERILATOR ?= verilator")
        lines.append("VERILATOR_ROOT ?= $(shell $(VERILATOR) --getenv VERILATOR_ROOT)")
        lines.append("")

        # Compiler flags — no VL_THREADED, C++17
        trace_cflags = ""
        if trace:
            trace_cflags = " -DVM_TRACE=1"
            if trace_type == 'fst':
                trace_cflags += " -DVM_TRACE_FST=1"

        lines.append("CXX ?= g++")
        lines.append(f"CXXFLAGS := -std=c++17 -O2 -I$(VERILATOR_ROOT)/include -I$(VERILATOR_ROOT)/include/vltstd -I$(DPI_DIR){trace_cflags}")
        if extra_cflags:
            lines.append(f"CXXFLAGS += {extra_cflags}")
        lines.append(f"LDFLAGS := -lpthread")
        if extra_ldflags:
            lines.append(f"LDFLAGS += {extra_ldflags}")
        lines.append("")

        # Verilator common flags
        verilator_common = "--cc -Mdir"
        if trace:
            verilator_common += " --trace" + ("-fst" if trace_type == 'fst' else "")

        # Phony targets
        all_binaries = ["$(STATIC_BINARY)"] + rm_binary_vars
        lines.append(f".PHONY: all clean")
        lines.append("")

        # ── Verilator library targets ─────────────────────────────────

        lines.append("# ═══ Verilator library archives ═══")
        lines.append("")

        # Static module lib
        static_obj_dir = f"$(BUILD_DIR)/{static_module.obj_dir_prefix}obj_dir"
        static_lib = f"{static_obj_dir}/V{static_module.top_module}__ALL.a"
        sources_str = " ".join(static_module.sources)
        include_str = " ".join(f"-I{d}" for d in static_module.include_dirs)
        vflags = " ".join(static_module.verilator_flags)
        if vflags:
            vflags = " " + vflags

        lines.append(f"# Static region: {static_module.name}")
        lines.append(f"{static_lib}: {sources_str}")
        lines.append(f"\t@mkdir -p {static_obj_dir}")
        lines.append(f"\t$(VERILATOR) {verilator_common} {static_obj_dir} --top-module {static_module.top_module} --public-flat-rw -Wno-WIDTHTRUNC{vflags} {include_str} {sources_str}")
        lines.append(f"\t$(MAKE) -C {static_obj_dir} -f V{static_module.top_module}.mk")
        lines.append("")

        # RM module libs
        rm_libs = {}  # rm.name -> lib_path
        for rm in rm_binaries:
            mod = rm.module
            obj_dir = f"$(BUILD_DIR)/{mod.obj_dir_prefix}obj_dir"
            lib_name = f"V{mod.top_module}__ALL.a"
            lib_path = f"{obj_dir}/{lib_name}"
            rm_libs[rm.name] = lib_path

            sources_str = " ".join(mod.sources)
            include_str = " ".join(f"-I{d}" for d in mod.include_dirs)
            vflags = " ".join(mod.verilator_flags)
            if vflags:
                vflags = " " + vflags

            lines.append(f"# RM: {rm.name}")
            lines.append(f"{lib_path}: {sources_str}")
            lines.append(f"\t@mkdir -p {obj_dir}")
            lines.append(f"\t$(VERILATOR) {verilator_common} {obj_dir} --top-module {mod.top_module} --public-flat-rw -Wno-WIDTHTRUNC{vflags} {include_str} {sources_str}")
            lines.append(f"\t$(MAKE) -C {obj_dir} -f V{mod.top_module}.mk")
            lines.append("")

        # ── Verilator support objects ─────────────────────────────────

        lines.append("# ═══ Verilator support objects ═══")
        lines.append("")
        lines.append("$(DPI_DIR)/verilated.o: $(VERILATOR_ROOT)/include/verilated.cpp")
        lines.append("\t$(CXX) $(CXXFLAGS) -c -o $@ $<")
        lines.append("")
        lines.append("$(DPI_DIR)/verilated_threads.o: $(VERILATOR_ROOT)/include/verilated_threads.cpp")
        lines.append("\t$(CXX) $(CXXFLAGS) -c -o $@ $<")
        lines.append("")

        support_objs = ["$(DPI_DIR)/verilated.o", "$(DPI_DIR)/verilated_threads.o"]

        if trace:
            if trace_type == 'fst':
                lines.append("$(DPI_DIR)/verilated_fst_c.o: $(VERILATOR_ROOT)/include/verilated_fst_c.cpp")
                lines.append("\t$(CXX) $(CXXFLAGS) -c -o $@ $<")
            else:
                lines.append("$(DPI_DIR)/verilated_vcd_c.o: $(VERILATOR_ROOT)/include/verilated_vcd_c.cpp")
                lines.append("\t$(CXX) $(CXXFLAGS) -c -o $@ $<")
            lines.append("")
            trace_obj = f"$(DPI_DIR)/verilated_{'fst' if trace_type == 'fst' else 'vcd'}_c.o"
            support_objs.append(trace_obj)

        # ── Static binary DPI objects ─────────────────────────────────

        lines.append("# ═══ Static binary C++ objects ═══")
        lines.append("")

        static_obj_dir_include = f"-I{static_obj_dir}"
        static_dpi_objs = []

        # Static driver (depends on static lib for generated headers)
        driver_obj = f"$(DPI_DIR)/static_driver.o"
        static_dpi_objs.append(driver_obj)
        lines.append(f"{driver_obj}: {static_driver_cpp} {static_lib}")
        lines.append(f"\t$(CXX) $(CXXFLAGS) {static_obj_dir_include} -c -o $@ $<")
        lines.append("")

        # Static-side DPI partition files (depend on static lib for headers)
        for cpp_file in static_dpi_cpp_files:
            cpp_path = Path(cpp_file)
            obj_name = cpp_path.stem + ".o"
            obj_path = f"$(DPI_DIR)/{obj_name}"
            static_dpi_objs.append(obj_path)

            lines.append(f"{obj_path}: {cpp_file} {static_lib}")
            lines.append(f"\t$(CXX) $(CXXFLAGS) {static_obj_dir_include} -c -o $@ $<")
            lines.append("")

        # ── Static binary link ────────────────────────────────────────

        lines.append("# ═══ Static binary ═══")
        lines.append("")

        static_all_objs = static_dpi_objs + support_objs
        objs_str = " ".join(static_all_objs)
        lines.append(f"$(STATIC_BINARY): {static_lib} {objs_str}")
        lines.append(f"\t$(CXX) $(CXXFLAGS) -o $@ {objs_str} {static_lib} $(LDFLAGS)")
        lines.append("")

        # ── Per-RM binary objects and link ────────────────────────────

        lines.append("# ═══ RM binaries ═══")
        lines.append("")

        for rm in rm_binaries:
            mod = rm.module
            rm_obj_dir = f"$(BUILD_DIR)/{mod.obj_dir_prefix}obj_dir"
            rm_obj_dir_include = f"-I{rm_obj_dir}"
            rm_lib = rm_libs[rm.name]

            rm_objs = []

            # RM driver object (depends on RM lib for generated headers)
            rm_driver_obj = f"$(BUILD_DIR)/rm/{rm.name}/rm_driver_{rm.name}.o"
            rm_objs.append(rm_driver_obj)
            lines.append(f"{rm_driver_obj}: {rm.driver_cpp} {rm_lib}")
            lines.append(f"\t@mkdir -p $(BUILD_DIR)/rm/{rm.name}")
            lines.append(f"\t$(CXX) $(CXXFLAGS) {rm_obj_dir_include} -c -o $@ $<")
            lines.append("")

            # RM-side DPI object (depends on RM lib for generated headers)
            rm_dpi_obj = f"$(BUILD_DIR)/rm/{rm.name}/dpi_rm_{rm.partition_name}.o"
            rm_objs.append(rm_dpi_obj)
            lines.append(f"{rm_dpi_obj}: {rm.dpi_rm_cpp} {rm_lib}")
            lines.append(f"\t@mkdir -p $(BUILD_DIR)/rm/{rm.name}")
            lines.append(f"\t$(CXX) $(CXXFLAGS) {rm_obj_dir_include} -c -o $@ $<")
            lines.append("")

            # Link RM binary
            rm_all_objs = rm_objs + support_objs
            rm_objs_str = " ".join(rm_all_objs)
            var_name = f"RM_BINARY_{rm.name.upper()}"
            lines.append(f"$({var_name}): {rm_lib} {rm_objs_str}")
            lines.append(f"\t@mkdir -p $(BUILD_DIR)/rm/{rm.name}")
            lines.append(f"\t$(CXX) $(CXXFLAGS) -o $@ {rm_objs_str} {rm_lib} $(LDFLAGS)")
            lines.append("")

        # ── Default and clean targets ─────────────────────────────────

        all_str = " ".join(all_binaries)
        lines.append(f"all: {all_str}")
        lines.append("")

        lines.append("clean:")
        lines.append(f"\trm -rf $(STATIC_BINARY) $(DPI_DIR)/*.o")
        lines.append(f"\trm -rf $(BUILD_DIR)/rm")
        lines.append(f"\trm -rf $(BUILD_DIR)/{static_module.obj_dir_prefix}obj_dir")
        for rm in rm_binaries:
            lines.append(f"\trm -rf $(BUILD_DIR)/{rm.module.obj_dir_prefix}obj_dir")
        lines.append("")

        output_path = self.build_dir / "Makefile"
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text("\n".join(lines))
        logger.info(f"Generated: {output_path}")
        return output_path
