// RM-side DPI functions for partition: rp_wide64
// Generated by partial_reconfiguration

#include "dpi_shm_channel.h"
#include <svdpi.h>

// Channel base from rm_driver_*.cpp
extern void* g_channel_base;
extern ShmPartitionHeader* g_channel_header;

extern "C" {

long long dpi_rm_rp_wide64_wide_in_recv_data() {
    ShmPortOverride* ovr = shm_to_rm_override(g_channel_base, 0);
    if (shm_load32(&ovr->active))
        return static_cast<long long>(shm_load64_relaxed(&ovr->value) & 0xFFFFFFFFFFFFull);
    return static_cast<long long>(shm_to_rm_inbox(g_channel_base, 0)->data & 0xFFFFFFFFFFFFull);
}

int dpi_rm_rp_wide64_wide_in_recv_valid() {
    ShmPortOverride* ovr = shm_to_rm_override(g_channel_base, 0);
    if (shm_load32(&ovr->active))
        return 1;
    return shm_to_rm_inbox(g_channel_base, 0)->valid ? 1 : 0;
}

long long dpi_rm_rp_wide64_full64_in_recv_data() {
    ShmPortOverride* ovr = shm_to_rm_override(g_channel_base, 1);
    if (shm_load32(&ovr->active))
        return static_cast<long long>(shm_load64_relaxed(&ovr->value));
    return static_cast<long long>(shm_to_rm_inbox(g_channel_base, 1)->data);
}

int dpi_rm_rp_wide64_full64_in_recv_valid() {
    ShmPortOverride* ovr = shm_to_rm_override(g_channel_base, 1);
    if (shm_load32(&ovr->active))
        return 1;
    return shm_to_rm_inbox(g_channel_base, 1)->valid ? 1 : 0;
}

void dpi_rm_rp_wide64_wide_out_send(long long data) {
    ShmPort* p = shm_from_rm_outbox(g_channel_base, g_channel_header->num_to_rm, 0);
    p->data = static_cast<uint64_t>(data & 0xFFFFFFFFFFFFull);
    p->valid = 1;
}

void dpi_rm_rp_wide64_full64_out_send(long long data) {
    ShmPort* p = shm_from_rm_outbox(g_channel_base, g_channel_header->num_to_rm, 1);
    p->data = static_cast<uint64_t>(data);
    p->valid = 1;
}

} // extern "C"