// Static-side DPI functions for partition: rp_wide64
// Generated by partial_reconfiguration

#include "dpi_shm_channel.h"
#include <svdpi.h>

// Partition base from static_driver.cpp
extern void* g_partition_bases[];

extern "C" {

void dpi_static_rp_wide64_wide_in_send(long long data) {
    ShmPort* p = shm_to_rm_outbox(g_partition_bases[0], 0);
    p->data = static_cast<uint64_t>(data & 0xFFFFFFFFFFFFull);
    p->valid = 1;
}

void dpi_static_rp_wide64_full64_in_send(long long data) {
    ShmPort* p = shm_to_rm_outbox(g_partition_bases[0], 1);
    p->data = static_cast<uint64_t>(data);
    p->valid = 1;
}

long long dpi_static_rp_wide64_wide_out_recv_data() {
    return static_cast<long long>(shm_from_rm_inbox(g_partition_bases[0], 2, 0)->data & 0xFFFFFFFFFFFFull);
}

int dpi_static_rp_wide64_wide_out_recv_valid() {
    return shm_from_rm_inbox(g_partition_bases[0], 2, 0)->valid ? 1 : 0;
}

long long dpi_static_rp_wide64_full64_out_recv_data() {
    return static_cast<long long>(shm_from_rm_inbox(g_partition_bases[0], 2, 1)->data);
}

int dpi_static_rp_wide64_full64_out_recv_valid() {
    return shm_from_rm_inbox(g_partition_bases[0], 2, 1)->valid ? 1 : 0;
}

} // extern "C"