// RM driver for wide64_rm (partition rp_wide64)
// Generated by partial_reconfiguration

#include "dpi_shm_channel.h"
#include "barrier_sync.h"

#include <verilated.h>
#include "Vwide64_rm_dpi_wrapper.h"

#include <cstring>
#include <iostream>
#include <sys/mman.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <unistd.h>

// Required by Verilator
double sc_time_stamp() { return 0; }

// Exported for DPI functions in dpi_rm_*.cpp
void* g_channel_base = nullptr;
ShmPartitionHeader* g_channel_header = nullptr;

static void* mmap_file(const char* path, size_t expected_size, int* fd_out) {
    int fd = open(path, O_RDWR);
    if (fd < 0) { perror(path); return nullptr; }
    struct stat st;
    fstat(fd, &st);
    size_t sz = (expected_size > 0) ? expected_size : (size_t)st.st_size;
    void* ptr = mmap(nullptr, sz, PROT_READ | PROT_WRITE, MAP_SHARED, fd, 0);
    if (ptr == MAP_FAILED) { perror("mmap"); close(fd); return nullptr; }
    if (fd_out) *fd_out = fd; else close(fd);
    return ptr;
}

int main(int argc, char** argv) {
    const char* shm_dir = nullptr;
    int partition_index = -1;
    for (int i = 1; i < argc; i++) {
        if (std::string(argv[i]) == "--shm-dir" && i + 1 < argc)
            shm_dir = argv[++i];
        else if (std::string(argv[i]) == "--partition-index" && i + 1 < argc)
            partition_index = std::stoi(argv[++i]);
    }
    if (!shm_dir || partition_index < 0) {
        std::cerr << "Usage: rm_binary --shm-dir DIR --partition-index N" << std::endl;
        return 1;
    }

    std::string dir(shm_dir);

    // Open partition channel
    int ch_fd = -1;
    std::string ch_path = dir + "/partition_" + std::to_string(partition_index) + ".shm";
    g_channel_base = mmap_file(ch_path.c_str(), 0, &ch_fd);
    if (!g_channel_base) return 1;
    g_channel_header = shm_header(g_channel_base);
    struct stat ch_st; fstat(ch_fd, &ch_st);
    size_t ch_size = ch_st.st_size;

    // Open barrier
    int br_fd = -1;
    ShmBarrier* barrier = (ShmBarrier*)mmap_file((dir + "/barrier.shm").c_str(), 4096, &br_fd);
    if (!barrier) return 1;

    // Create RM model
    auto ctx = new VerilatedContext;
    auto model = new Vwide64_rm_dpi_wrapper(ctx);

    // Init barrier sense from current global sense
    uint32_t local_sense = __atomic_load_n(&barrier->sense, __ATOMIC_ACQUIRE);

    // Signal ready to static binary
    shm_store32(&g_channel_header->rm_ready, 1);

    // Main simulation loop
    while (true) {
        // Check quit before barrier (allows clean exit during reconfig)
        if (shm_load32(&g_channel_header->quit))
            break;

        model->clk = 0;
        model->eval();
        barrier_wait(barrier, &local_sense);  // 1: negedge done

        barrier_wait(barrier, &local_sense);  // 2: swap done

        model->clk = 1;
        model->eval();
        barrier_wait(barrier, &local_sense);  // 3: posedge done
    }

    // Cleanup
    delete model;
    delete ctx;
    munmap(g_channel_base, ch_size); close(ch_fd);
    munmap(barrier, 4096); close(br_fd);
    return 0;
}