// Static-side DPI bridge for partition: rp_dummy
// Replaces weird_rm in static region
// Generated by partial_reconfiguration DPI bridge generator

`timescale 1ns/1ps

module weird_rm (
    input wire sys_input,
    output reg [31:0] data_out
);


    import "DPI-C" function int dpi_static_rp_dummy_data_out_recv_data();
    import "DPI-C" function int dpi_static_rp_dummy_data_out_recv_valid();

    // Receive outputs from RM via DPI channels
    always @(posedge sys_input) begin
        if (dpi_static_rp_dummy_data_out_recv_valid())
            data_out <= dpi_static_rp_dummy_data_out_recv_data();
    end

endmodule