from typing import Dict, Any, Optional, List
from pathlib import Path
import hashlib


class GreyboxGenerator:
    """
    Generates SystemVerilog greybox modules for partition interfaces.

    A greybox is a placeholder module that matches the partition interface
    but drives all outputs to a constant value (like real FPGA greybox
    modules in Vivado DFX).
    """

    MODULE_TEMPLATE = '''\
// Auto-generated greybox module for partition: {partition_name}
// Generated by PR simulation system
//
// This module drives all outputs to constant values.
// Inputs are connected but ignored.

`timescale 1ns/1ps

module {module_name} (
{port_declarations}
);

{parameter_declarations}

{output_assignments}

{input_sinks}

endmodule
'''

    def __init__(self, build_dir: str = None, output_value: int = 0):
        """
        Initialize greybox generator.

        Parameters
        ----------
        build_dir : str, optional
            Directory to write generated files
        output_value : int
            Value to drive on all outputs (default 0)
        """
        self.build_dir = Path(build_dir) if build_dir else Path('build/pr/greybox')
        self.output_value = output_value
        self._generated_files: Dict[str, Path] = {}

    def generate(
        self,
        partition_name: str,
        interface: Dict[str, Dict[str, Any]],
        clocks: List[str] = None,
        resets: List[Dict[str, Any]] = None,
        module_name: str = None,
        output_value: int = None
    ) -> Path:
        """
        Generate a greybox module for a partition interface.

        Parameters
        ----------
        partition_name : str
            Name of the partition (used in comments and default module name)
        interface : dict
            Partition interface definition
        clocks : list, optional
            List of clock signal names
        resets : list, optional
            List of reset definitions (each with 'name' and optional 'polarity')
        module_name : str, optional
            Module name (default: {partition_name}_greybox)
        output_value : int, optional
            Override default output value

        Returns
        -------
        Path
            Path to generated SystemVerilog file
        """
        if module_name is None:
            module_name = f"{partition_name}_greybox"

        if output_value is None:
            output_value = self.output_value

        if clocks is None:
            clocks = []

        if resets is None:
            resets = []

        content = self._generate_module(
            partition_name=partition_name,
            module_name=module_name,
            interface=interface,
            clocks=clocks,
            resets=resets,
            output_value=output_value
        )

        self.build_dir.mkdir(parents=True, exist_ok=True)

        output_path = self.build_dir / f"{module_name}.sv"
        output_path.write_text(content)

        self._generated_files[partition_name] = output_path
        return output_path

    def _generate_module(
        self,
        partition_name: str,
        module_name: str,
        interface: Dict[str, Dict[str, Any]],
        clocks: List[str],
        resets: List[Dict[str, Any]],
        output_value: int
    ) -> str:
        """Generate SystemVerilog module content."""
        port_decls = []
        param_decls = []
        output_assigns = []
        input_sinks = []

        for clk in clocks:
            port_decls.append(f"    input wire {clk}")

        for rst in resets:
            rst_name = rst if isinstance(rst, str) else rst.get('name', 'rst')
            port_decls.append(f"    input wire {rst_name}")

        for port_name, port_def in interface.items():
            port_type = port_def.get('type', 'gpio')
            direction = port_def.get('direction', 'input')

            if port_type == 'gpio':
                width = port_def.get('width', 1)
                decl, assigns, sinks = self._generate_gpio_port(
                    port_name, direction, width, output_value
                )
                port_decls.append(decl)
                output_assigns.extend(assigns)
                input_sinks.extend(sinks)

            elif port_type == 'sb':
                dw = port_def.get('dw', 256)
                decl, assigns, sinks = self._generate_sb_port(
                    port_name, direction, dw, output_value
                )
                port_decls.append(decl)
                output_assigns.extend(assigns)
                input_sinks.extend(sinks)

            elif port_type == 'axi':
                dw = port_def.get('dw', 32)
                aw = port_def.get('aw', 32)
                idw = port_def.get('idw', 4)
                decl, assigns, sinks = self._generate_axi_port(
                    port_name, direction, dw, aw, idw, output_value
                )
                port_decls.append(decl)
                output_assigns.extend(assigns)
                input_sinks.extend(sinks)

            elif port_type == 'axil':
                dw = port_def.get('dw', 32)
                aw = port_def.get('aw', 32)
                decl, assigns, sinks = self._generate_axil_port(
                    port_name, direction, dw, aw, output_value
                )
                port_decls.append(decl)
                output_assigns.extend(assigns)
                input_sinks.extend(sinks)

            else:
                width = port_def.get('width', port_def.get('dw', 1))
                decl, assigns, sinks = self._generate_gpio_port(
                    port_name, direction, width, output_value
                )
                port_decls.append(decl)
                output_assigns.extend(assigns)
                input_sinks.extend(sinks)
        return self.MODULE_TEMPLATE.format(
            partition_name=partition_name,
            module_name=module_name,
            port_declarations=',\n'.join(port_decls),
            parameter_declarations='\n'.join(param_decls) if param_decls else '// No parameters',
            output_assignments='\n'.join(output_assigns) if output_assigns else '// No outputs',
            input_sinks='\n'.join(input_sinks) if input_sinks else '// No inputs'
        )

    def _generate_gpio_port(
        self,
        name: str,
        direction: str,
        width: int,
        output_value: int
    ) -> tuple:
        """Generate GPIO port declaration and assignments."""
        width_str = f"[{width-1}:0] " if width > 1 else ""

        if direction in ['output', 'manager']:
            decl = f"    output logic {width_str}{name}"
            assigns = [f"    assign {name} = {width}'d{output_value};"]
            sinks = []
        else:
            decl = f"    input wire {width_str}{name}"
            assigns = []
            sinks = [f"    // Input {name} is connected but ignored"]

        return decl, assigns, sinks

    def _generate_sb_port(
        self,
        name: str,
        direction: str,
        dw: int,
        output_value: int
    ) -> tuple:
        """Generate streaming port declaration and assignments."""
        ports = []
        assigns = []
        sinks = []

        if direction in ['output', 'manager']:
            ports.append(f"    output logic [{dw-1}:0] {name}_data")
            ports.append(f"    output logic [31:0] {name}_dest")
            ports.append(f"    output logic {name}_last")
            ports.append(f"    output logic {name}_valid")
            ports.append(f"    input wire {name}_ready")

            assigns.append(f"    assign {name}_data = {dw}'d{output_value};")
            assigns.append(f"    assign {name}_dest = 32'd0;")
            assigns.append(f"    assign {name}_last = 1'b0;")
            assigns.append(f"    assign {name}_valid = 1'b0;  // Greybox never sends")
        else:
            ports.append(f"    input wire [{dw-1}:0] {name}_data")
            ports.append(f"    input wire [31:0] {name}_dest")
            ports.append(f"    input wire {name}_last")
            ports.append(f"    input wire {name}_valid")
            ports.append(f"    output logic {name}_ready")

            assigns.append(f"    assign {name}_ready = 1'b1;  // Greybox always accepts")
            sinks.append(f"    // Input {name} data is accepted but ignored")

        decl = ',\n'.join(ports)
        return decl, assigns, sinks

    def _generate_axi_port(
        self,
        name: str,
        direction: str,
        dw: int,
        aw: int,
        idw: int,
        output_value: int
    ) -> tuple:
        """Generate AXI port declaration and assignments."""
        ports = []
        assigns = []
        sinks = []

        is_manager = direction in ['output', 'manager']

        ports.append(f"    {'output logic' if is_manager else 'input wire'} [{idw-1}:0] {name}_awid")
        ports.append(f"    {'output logic' if is_manager else 'input wire'} [{aw-1}:0] {name}_awaddr")
        ports.append(f"    {'output logic' if is_manager else 'input wire'} [7:0] {name}_awlen")
        ports.append(f"    {'output logic' if is_manager else 'input wire'} {name}_awvalid")
        ports.append(f"    {'input wire' if is_manager else 'output logic'} {name}_awready")

        ports.append(f"    {'output logic' if is_manager else 'input wire'} [{dw-1}:0] {name}_wdata")
        ports.append(f"    {'output logic' if is_manager else 'input wire'} [{dw//8-1}:0] {name}_wstrb")
        ports.append(f"    {'output logic' if is_manager else 'input wire'} {name}_wlast")
        ports.append(f"    {'output logic' if is_manager else 'input wire'} {name}_wvalid")
        ports.append(f"    {'input wire' if is_manager else 'output logic'} {name}_wready")

        ports.append(f"    {'input wire' if is_manager else 'output logic'} [{idw-1}:0] {name}_bid")
        ports.append(f"    {'input wire' if is_manager else 'output logic'} [1:0] {name}_bresp")
        ports.append(f"    {'input wire' if is_manager else 'output logic'} {name}_bvalid")
        ports.append(f"    {'output logic' if is_manager else 'input wire'} {name}_bready")

        ports.append(f"    {'output logic' if is_manager else 'input wire'} [{idw-1}:0] {name}_arid")
        ports.append(f"    {'output logic' if is_manager else 'input wire'} [{aw-1}:0] {name}_araddr")
        ports.append(f"    {'output logic' if is_manager else 'input wire'} [7:0] {name}_arlen")
        ports.append(f"    {'output logic' if is_manager else 'input wire'} {name}_arvalid")
        ports.append(f"    {'input wire' if is_manager else 'output logic'} {name}_arready")

        ports.append(f"    {'input wire' if is_manager else 'output logic'} [{idw-1}:0] {name}_rid")
        ports.append(f"    {'input wire' if is_manager else 'output logic'} [{dw-1}:0] {name}_rdata")
        ports.append(f"    {'input wire' if is_manager else 'output logic'} [1:0] {name}_rresp")
        ports.append(f"    {'input wire' if is_manager else 'output logic'} {name}_rlast")
        ports.append(f"    {'input wire' if is_manager else 'output logic'} {name}_rvalid")
        ports.append(f"    {'output logic' if is_manager else 'input wire'} {name}_rready")

        if is_manager:
            assigns.extend([
                f"    assign {name}_awid = {idw}'d0;",
                f"    assign {name}_awaddr = {aw}'d0;",
                f"    assign {name}_awlen = 8'd0;",
                f"    assign {name}_awvalid = 1'b0;",
                f"    assign {name}_wdata = {dw}'d{output_value};",
                f"    assign {name}_wstrb = {dw//8}'d0;",
                f"    assign {name}_wlast = 1'b0;",
                f"    assign {name}_wvalid = 1'b0;",
                f"    assign {name}_bready = 1'b1;",
                f"    assign {name}_arid = {idw}'d0;",
                f"    assign {name}_araddr = {aw}'d0;",
                f"    assign {name}_arlen = 8'd0;",
                f"    assign {name}_arvalid = 1'b0;",
                f"    assign {name}_rready = 1'b1;",
            ])
        else:
            assigns.extend([
                f"    assign {name}_awready = 1'b1;",
                f"    assign {name}_wready = 1'b1;",
                f"    assign {name}_bid = {idw}'d0;",
                f"    assign {name}_bresp = 2'b00;",
                f"    assign {name}_bvalid = 1'b0;",
                f"    assign {name}_arready = 1'b1;",
                f"    assign {name}_rid = {idw}'d0;",
                f"    assign {name}_rdata = {dw}'d{output_value};",
                f"    assign {name}_rresp = 2'b00;",
                f"    assign {name}_rlast = 1'b0;",
                f"    assign {name}_rvalid = 1'b0;",
            ])

        decl = ',\n'.join(ports)
        return decl, assigns, sinks

    def _generate_axil_port(
        self,
        name: str,
        direction: str,
        dw: int,
        aw: int,
        output_value: int
    ) -> tuple:
        """Generate AXI-Lite port declaration and assignments."""
        ports = []
        assigns = []
        sinks = []

        is_manager = direction in ['output', 'manager']

        ports.append(f"    {'output logic' if is_manager else 'input wire'} [{aw-1}:0] {name}_awaddr")
        ports.append(f"    {'output logic' if is_manager else 'input wire'} {name}_awvalid")
        ports.append(f"    {'input wire' if is_manager else 'output logic'} {name}_awready")

        ports.append(f"    {'output logic' if is_manager else 'input wire'} [{dw-1}:0] {name}_wdata")
        ports.append(f"    {'output logic' if is_manager else 'input wire'} [{dw//8-1}:0] {name}_wstrb")
        ports.append(f"    {'output logic' if is_manager else 'input wire'} {name}_wvalid")
        ports.append(f"    {'input wire' if is_manager else 'output logic'} {name}_wready")

        ports.append(f"    {'input wire' if is_manager else 'output logic'} [1:0] {name}_bresp")
        ports.append(f"    {'input wire' if is_manager else 'output logic'} {name}_bvalid")
        ports.append(f"    {'output logic' if is_manager else 'input wire'} {name}_bready")
        ports.append(f"    {'output logic' if is_manager else 'input wire'} [{aw-1}:0] {name}_araddr")
        ports.append(f"    {'output logic' if is_manager else 'input wire'} {name}_arvalid")
        ports.append(f"    {'input wire' if is_manager else 'output logic'} {name}_arready")
        ports.append(f"    {'input wire' if is_manager else 'output logic'} [{dw-1}:0] {name}_rdata")
        ports.append(f"    {'input wire' if is_manager else 'output logic'} [1:0] {name}_rresp")
        ports.append(f"    {'input wire' if is_manager else 'output logic'} {name}_rvalid")
        ports.append(f"    {'output logic' if is_manager else 'input wire'} {name}_rready")

        if is_manager:
            assigns.extend([
                f"    assign {name}_awaddr = {aw}'d0;",
                f"    assign {name}_awvalid = 1'b0;",
                f"    assign {name}_wdata = {dw}'d{output_value};",
                f"    assign {name}_wstrb = {dw//8}'d0;",
                f"    assign {name}_wvalid = 1'b0;",
                f"    assign {name}_bready = 1'b1;",
                f"    assign {name}_araddr = {aw}'d0;",
                f"    assign {name}_arvalid = 1'b0;",
                f"    assign {name}_rready = 1'b1;",
            ])
        else:
            assigns.extend([
                f"    assign {name}_awready = 1'b1;",
                f"    assign {name}_wready = 1'b1;",
                f"    assign {name}_bresp = 2'b00;",
                f"    assign {name}_bvalid = 1'b0;",
                f"    assign {name}_arready = 1'b1;",
                f"    assign {name}_rdata = {dw}'d{output_value};",
                f"    assign {name}_rresp = 2'b00;",
                f"    assign {name}_rvalid = 1'b0;",
            ])

        decl = ',\n'.join(ports)
        return decl, assigns, sinks

    def get_generated_path(self, partition_name: str) -> Optional[Path]:
        """Get path to generated greybox file for a partition."""
        return self._generated_files.get(partition_name)

    def cleanup(self):
        """Remove all generated files."""
        for path in self._generated_files.values():
            if path.exists():
                path.unlink()
        self._generated_files.clear()
