from typing import Dict, List, Optional, Any
from pathlib import Path
from dataclasses import dataclass
import logging

from .rtl_parser import ModuleInfo, PortInfo, PortType

logger = logging.getLogger(__name__)


@dataclass
class PartitionBoundaryPort:
    """A port on the partition boundary."""
    name: str
    width: int
    direction: str  # 'to_rm' (static→RM) or 'from_rm' (RM→static)


@dataclass
class PartitionBoundary:
    """Definition of a partition boundary."""
    partition_name: str
    rm_module_name: str
    ports: List[PartitionBoundaryPort]
    clock_name: str = 'clk'
    reset_name: str = 'rst_n'
    reset_active_low: bool = True

    @classmethod
    def from_module_info(cls, partition_name: str, module_info: ModuleInfo,
                         clock_name: str = 'clock', reset_name: str = None):
        """
        Create partition boundary from parsed RM module info.

        All RM input ports (except clock/reset) become 'to_rm' boundary ports.
        All RM output ports become 'from_rm' boundary ports.
        """
        ports = []
        for port in module_info.ports:
            if port.port_type in [PortType.CLOCK, PortType.RESET]:
                continue
            if port.name == clock_name or port.name == reset_name:
                continue

            direction = 'to_rm' if port.direction == 'input' else 'from_rm'
            ports.append(PartitionBoundaryPort(
                name=port.name,
                width=port.width,
                direction=direction
            ))

        return cls(
            partition_name=partition_name,
            rm_module_name=module_info.name,
            ports=ports,
            clock_name=clock_name,
            reset_name=reset_name or 'rst_n'
        )


class QueueBridgeGenerator:
    """
    Generates queue-based bridge modules for partition boundaries.

    Generates two modules:
    1. Static-side bridge: replaces RM in static region, uses queues
    2. RM-side wrapper: wraps RM with queue interfaces
    """

    def __init__(self, build_dir: str = None, queue_dir: str = None):
        self.build_dir = Path(build_dir) if build_dir else Path('build/pr/bridges')
        self.build_dir.mkdir(parents=True, exist_ok=True)
        self.queue_dir = Path(queue_dir).resolve() if queue_dir else Path.cwd() / 'build' / 'queues'
        self.queue_dir.mkdir(parents=True, exist_ok=True)

    def generate_static_side_bridge(
        self,
        boundary: PartitionBoundary,
        queue_prefix: str = None
    ) -> Path:
        """
        Generate the static-side queue bridge.

        This module:
        - Has the same ports as the original RM (so it can replace it)
        - Sends input values to queues
        - Receives output values from queues

        Parameters
        ----------
        boundary : PartitionBoundary
            Partition boundary definition
        queue_prefix : str
            Prefix for queue file names (default: partition_name)

        Returns
        -------
        Path
            Path to generated SystemVerilog file
        """
        if queue_prefix is None:
            queue_prefix = boundary.partition_name
        module_name = boundary.rm_module_name

        lines = []
        lines.append(f"// Static-side queue bridge for partition: {boundary.partition_name}")
        lines.append(f"// Replaces {boundary.rm_module_name} in static region")
        lines.append("// Generated by Switchboard PR simulation")
        lines.append("")
        lines.append("`timescale 1ns/1ps")
        lines.append("")
        lines.append('`include "switchboard.vh"')
        lines.append("")

        lines.append(f"module {module_name} (")
        lines.append(f"    input wire {boundary.clock_name},")

        port_lines = []
        for port in boundary.ports:
            width_str = f"[{port.width-1}:0] " if port.width > 1 else ""
            if port.direction == 'to_rm':
                port_lines.append(f"    input wire {width_str}{port.name}")
            else:
                port_lines.append(f"    output reg {width_str}{port.name}")

        lines.append(",\n".join(port_lines))
        lines.append(");")
        lines.append("")

        lines.append("    // Internal reset (active low, always deasserted)")
        lines.append("    wire reset_n = 1'b1;")
        lines.append("    wire reset = 1'b0;")
        lines.append("")
        to_rm_ports = [p for p in boundary.ports if p.direction == 'to_rm']
        from_rm_ports = [p for p in boundary.ports if p.direction == 'from_rm']

        if to_rm_ports:
            total_input_width = sum(p.width for p in to_rm_ports)
            lines.append(f"    // Input data to send to RM ({total_input_width} bits)")

            lines.append(f"    `SB_WIRES(to_rm, {total_input_width});")
            to_rm_queue = self.queue_dir / f"{queue_prefix}_to_rm.q"
            lines.append(f"    sb_to_queue_sim #(")
            lines.append(f"        .READY_MODE_DEFAULT(1),")
            lines.append(f"        .DW({total_input_width}),")
            lines.append(f"        .FILE(\"{to_rm_queue}\")")
            lines.append(f"    ) to_rm_sb_inst (")
            lines.append(f"        .clk({boundary.clock_name}),")
            lines.append(f"        .reset(reset),")
            lines.append(f"        .data(to_rm_data),")
            lines.append(f"        .dest(to_rm_dest),")
            lines.append(f"        .last(to_rm_last),")
            lines.append(f"        .ready(to_rm_ready),")
            lines.append(f"        .valid(to_rm_valid)")
            lines.append(f"    );")
            lines.append("")

            pack_parts = []
            for port in to_rm_ports:
                pack_parts.append(port.name)
            lines.append(f"    // Pack inputs and drive TX signals")
            lines.append(f"    assign to_rm_data = {{{', '.join(reversed(pack_parts))}}};")
            lines.append("    assign to_rm_dest = 32'd0;")
            lines.append("    assign to_rm_last = 1'b1;")
            lines.append("    assign to_rm_valid = 1'b1;")
            lines.append("")

        if from_rm_ports:
            total_output_width = sum(p.width for p in from_rm_ports)
            lines.append(f"    // Output data received from RM ({total_output_width} bits)")

            lines.append(f"    `SB_WIRES(from_rm, {total_output_width});")
            from_rm_queue = self.queue_dir / f"{queue_prefix}_from_rm.q"
            lines.append(f"    queue_to_sb_sim #(")
            lines.append(f"        .VALID_MODE_DEFAULT(1),")
            lines.append(f"        .DW({total_output_width}),")
            lines.append(f"        .FILE(\"{from_rm_queue}\")")
            lines.append(f"    ) from_rm_sb_inst (")
            lines.append(f"        .clk({boundary.clock_name}),")
            lines.append(f"        .reset(reset),")
            lines.append(f"        .data(from_rm_data),")
            lines.append(f"        .dest(from_rm_dest),")
            lines.append(f"        .last(from_rm_last),")
            lines.append(f"        .ready(from_rm_ready),")
            lines.append(f"        .valid(from_rm_valid)")
            lines.append(f"    );")
            lines.append("")
            lines.append("    assign from_rm_ready = 1'b1;")
            lines.append("")

            lines.append("    // Unpack received data to output ports")
            lines.append(f"    always @(posedge {boundary.clock_name}) begin")
            lines.append("        if (from_rm_valid) begin")
            offset = 0
            for port in from_rm_ports:
                if port.width == 1:
                    lines.append(f"            {port.name} <= from_rm_data[{offset}];")
                else:
                    lines.append(f"            {port.name} <= from_rm_data[{offset + port.width - 1}:{offset}];")
                offset += port.width
            lines.append("        end")
            lines.append("    end")
            lines.append("")

        lines.append("endmodule")

        output_path = self.build_dir / f"{module_name}.sv"
        output_path.write_text("\n".join(lines))
        logger.info(f"Generated static-side bridge: {output_path}")
        return output_path

    def generate_rm_side_wrapper(
        self,
        boundary: PartitionBoundary,
        rm_sources: List[str] = None,
        queue_prefix: str = None,
        rm_module_name: str = None,
        include_umi: bool = True,
        umi_dw: int = 256,
        umi_aw: int = 64,
        umi_cw: int = 32
    ) -> Path:
        """
        Generate the RM-side queue wrapper with optional UMI interface.

        This module:
        - Wraps the real RM module
        - Receives inputs from partition queues, drives them to RM
        - Reads RM outputs, sends them to partition queues
        - Optionally provides UMI interface for Python to read/write RM signals

        Parameters
        ----------
        boundary : PartitionBoundary
            Partition boundary definition
        rm_sources : list
            RM source files (for include reference)
        queue_prefix : str
            Prefix for queue file names (default: partition_name)
        rm_module_name : str
            Name of the RM module to wrap (default: boundary.rm_module_name)
            Use this to wrap variant RMs that have the same interface
        include_umi : bool
            Include UMI interface for Python access (default: True)
        umi_dw, umi_aw, umi_cw : int
            UMI interface parameters

        Returns
        -------
        Path
            Path to generated SystemVerilog file
        """
        if queue_prefix is None:
            queue_prefix = boundary.partition_name

        actual_rm_name = rm_module_name or boundary.rm_module_name
        wrapper_module_name = f"{actual_rm_name}_queue_wrapper"

        lines = []
        lines.append(f"// RM-side queue wrapper for partition: {boundary.partition_name}")
        lines.append(f"// Wraps {actual_rm_name} with queue + UMI interfaces")
        lines.append("// Generated by Switchboard PR simulation")
        lines.append("//")
        lines.append("// Queue interface: connects to static region via partition boundary")
        lines.append("// UMI interface: allows Python to directly access RM signals")
        lines.append("")
        lines.append("`timescale 1ns/1ps")
        lines.append("")
        lines.append('`include "switchboard.vh"')
        lines.append("")

        lines.append(f"module {wrapper_module_name} #(")
        lines.append(f"    parameter DW = {umi_dw},")
        lines.append(f"    parameter AW = {umi_aw},")
        lines.append(f"    parameter CW = {umi_cw}")
        lines.append(") (")
        lines.append(f"    input wire clk,")
        lines.append(f"    input wire rst_n,")
        lines.append("")

        if include_umi:
            lines.append("    // UMI Request interface (for Python access)")
            lines.append("    input  wire [CW-1:0]  req_cmd,")
            lines.append("    input  wire [AW-1:0]  req_dstaddr,")
            lines.append("    input  wire [AW-1:0]  req_srcaddr,")
            lines.append("    input  wire [DW-1:0]  req_data,")
            lines.append("    input  wire           req_valid,")
            lines.append("    output reg            req_ready,")
            lines.append("")
            lines.append("    // UMI Response interface")
            lines.append("    output reg  [CW-1:0]  resp_cmd,")
            lines.append("    output reg  [AW-1:0]  resp_dstaddr,")
            lines.append("    output reg  [AW-1:0]  resp_srcaddr,")
            lines.append("    output reg  [DW-1:0]  resp_data,")
            lines.append("    output reg            resp_valid,")
            lines.append("    input  wire           resp_ready")

        lines.append(");")
        lines.append("")

        to_rm_ports = [p for p in boundary.ports if p.direction == 'to_rm']
        from_rm_ports = [p for p in boundary.ports if p.direction == 'from_rm']

        if to_rm_ports:
            lines.append("    // Registers to hold input values (from queue or UMI)")
            for port in to_rm_ports:
                width_str = f"[{port.width-1}:0] " if port.width > 1 else ""
                lines.append(f"    reg {width_str}{port.name}_reg;")
            lines.append("")

            total_input_width = sum(p.width for p in to_rm_ports)
            lines.append(f"    // Queue interface to receive from static region")
            lines.append(f"    `SB_WIRES(from_static, {total_input_width});")
            to_rm_queue = self.queue_dir / f"{queue_prefix}_to_rm.q"
            lines.append(f"    queue_to_sb_sim #(")
            lines.append(f"        .VALID_MODE_DEFAULT(1),")
            lines.append(f"        .DW({total_input_width}),")
            lines.append(f"        .FILE(\"{to_rm_queue}\")")
            lines.append(f"    ) from_static_sb_inst (")
            lines.append(f"        .clk(clk),")
            lines.append(f"        .reset(~rst_n),")
            lines.append(f"        .data(from_static_data),")
            lines.append(f"        .dest(from_static_dest),")
            lines.append(f"        .last(from_static_last),")
            lines.append(f"        .ready(from_static_ready),")
            lines.append(f"        .valid(from_static_valid)")
            lines.append(f"    );")
            lines.append("")
            lines.append("    assign from_static_ready = 1'b1;")
            lines.append("")
        if from_rm_ports:
            lines.append("    // Wires for RM outputs")
            for port in from_rm_ports:
                width_str = f"[{port.width-1}:0] " if port.width > 1 else ""
                lines.append(f"    wire {width_str}{port.name}_wire;")
            lines.append("")

        lines.append(f"    // Instantiate the real RM: {actual_rm_name}")
        lines.append(f"    {actual_rm_name} u_rm (")
        lines.append(f"        .{boundary.clock_name}(clk),")

        port_connections = []
        for port in to_rm_ports:
            port_connections.append(f"        .{port.name}({port.name}_reg)")
        for port in from_rm_ports:
            port_connections.append(f"        .{port.name}({port.name}_wire)")

        lines.append(",\n".join(port_connections))
        lines.append("    );")
        lines.append("")

        if from_rm_ports:
            total_output_width = sum(p.width for p in from_rm_ports)
            lines.append(f"    // Queue interface to send outputs to static region")
            lines.append(f"    `SB_WIRES(to_static, {total_output_width});")
            from_rm_queue = self.queue_dir / f"{queue_prefix}_from_rm.q"
            lines.append(f"    sb_to_queue_sim #(")
            lines.append(f"        .READY_MODE_DEFAULT(1),")
            lines.append(f"        .DW({total_output_width}),")
            lines.append(f"        .FILE(\"{from_rm_queue}\")")
            lines.append(f"    ) to_static_sb_inst (")
            lines.append(f"        .clk(clk),")
            lines.append(f"        .reset(~rst_n),")
            lines.append(f"        .data(to_static_data),")
            lines.append(f"        .dest(to_static_dest),")
            lines.append(f"        .last(to_static_last),")
            lines.append(f"        .ready(to_static_ready),")
            lines.append(f"        .valid(to_static_valid)")
            lines.append(f"    );")
            lines.append("")

            pack_parts = [f"{p.name}_wire" for p in from_rm_ports]
            lines.append(f"    // Pack outputs and drive TX signals")
            lines.append(f"    assign to_static_data = {{{', '.join(reversed(pack_parts))}}};")
            lines.append("    assign to_static_dest = 32'd0;")
            lines.append("    assign to_static_last = 1'b1;")
            lines.append("    assign to_static_valid = 1'b1;")
            lines.append("")

        if include_umi:
            lines.append("    // UMI opcodes")
            lines.append("    localparam [4:0] UMI_REQ_READ    = 5'h01;")
            lines.append("    localparam [4:0] UMI_REQ_WRITE   = 5'h03;")
            lines.append("    localparam [4:0] UMI_REQ_POSTED  = 5'h05;")
            lines.append("    localparam [4:0] UMI_RESP_READ   = 5'h02;")
            lines.append("    localparam [4:0] UMI_RESP_WRITE  = 5'h04;")
            lines.append("")
            lines.append("    wire [4:0] opcode = req_cmd[4:0];")
            lines.append("    wire [15:0] addr = req_dstaddr[15:0];")
            lines.append("    wire is_read  = (opcode == UMI_REQ_READ);")
            lines.append("    wire is_write = (opcode == UMI_REQ_WRITE) || (opcode == UMI_REQ_POSTED);")
            lines.append("")
            lines.append("    // UMI override flags - when set, UMI value takes priority over queue")
            lines.append("    // This allows Python tests to control inputs without queue overwrites")
            for port in to_rm_ports:
                lines.append(f"    reg {port.name}_umi_override;")
            lines.append("")
            lines.append("    // UMI state machine")
            lines.append("    localparam S_IDLE = 2'd0, S_RESPOND = 2'd1;")
            lines.append("    reg [1:0] state;")
            lines.append("")
            lines.append("    always @(posedge clk or negedge rst_n) begin")
            lines.append("        if (!rst_n) begin")
            lines.append("            state <= S_IDLE;")
            lines.append("            req_ready <= 1'b1;")
            lines.append("            resp_valid <= 1'b0;")
            lines.append("            resp_cmd <= 0;")
            lines.append("            resp_dstaddr <= 0;")
            lines.append("            resp_srcaddr <= 0;")
            lines.append("            resp_data <= 0;")

            for port in to_rm_ports:
                lines.append(f"            {port.name}_reg <= 0;")
                lines.append(f"            {port.name}_umi_override <= 1'b0;")

            lines.append("        end else begin")
            if to_rm_ports:
                lines.append("            // Update from queue ONLY if not overridden by UMI")
                lines.append("            if (from_static_valid) begin")
                offset = 0
                for port in to_rm_ports:
                    if port.width == 1:
                        lines.append(f"                if (!{port.name}_umi_override) {port.name}_reg <= from_static_data[{offset}];")
                    else:
                        lines.append(f"                if (!{port.name}_umi_override) {port.name}_reg <= from_static_data[{offset + port.width - 1}:{offset}];")
                    offset += port.width
                lines.append("            end")
                lines.append("")
            lines.append("            // UMI state machine (sets override flag on writes)")
            lines.append("            case (state)")
            lines.append("                S_IDLE: begin")
            lines.append("                    req_ready <= 1'b1;")
            lines.append("                    if (req_valid && req_ready) begin")
            lines.append("                        req_ready <= 1'b0;")
            lines.append("                        resp_dstaddr <= req_srcaddr;")
            lines.append("                        resp_srcaddr <= req_dstaddr;")
            lines.append("")
            lines.append("                        if (is_read) begin")
            lines.append("                            resp_cmd <= {req_cmd[CW-1:5], UMI_RESP_READ};")
            lines.append("                            case (addr)")

            addr = 0
            for port in to_rm_ports:
                lines.append(f"                                16'h{addr:04X}: resp_data <= {{{{(DW-{port.width}){{1'b0}}}}, {port.name}_reg}};")
                addr += 8
            for port in from_rm_ports:
                lines.append(f"                                16'h{addr:04X}: resp_data <= {{{{(DW-{port.width}){{1'b0}}}}, {port.name}_wire}};")
                addr += 8

            lines.append("                                default: resp_data <= 0;")
            lines.append("                            endcase")
            lines.append("                            resp_valid <= 1'b1;")
            lines.append("                            state <= S_RESPOND;")
            lines.append("                        end else if (is_write) begin")
            lines.append("                            resp_cmd <= {req_cmd[CW-1:5], UMI_RESP_WRITE};")
            lines.append("                            case (addr)")

            addr = 0
            for port in to_rm_ports:
                if port.width == 1:
                    lines.append(f"                                16'h{addr:04X}: begin {port.name}_reg <= req_data[0]; {port.name}_umi_override <= 1'b1; end")
                else:
                    lines.append(f"                                16'h{addr:04X}: begin {port.name}_reg <= req_data[{port.width-1}:0]; {port.name}_umi_override <= 1'b1; end")
                addr += 8
            for port in from_rm_ports:
                addr += 8

            lines.append("                                default: ;")
            lines.append("                            endcase")
            lines.append("                            resp_data <= 0;")
            lines.append("                            resp_valid <= 1'b1;")
            lines.append("                            state <= S_RESPOND;")
            lines.append("                        end")
            lines.append("                    end")
            lines.append("                end")
            lines.append("")
            lines.append("                S_RESPOND: begin")
            lines.append("                    if (resp_valid && resp_ready) begin")
            lines.append("                        resp_valid <= 1'b0;")
            lines.append("                        req_ready <= 1'b1;")
            lines.append("                        state <= S_IDLE;")
            lines.append("                    end")
            lines.append("                end")
            lines.append("")
            lines.append("                default: state <= S_IDLE;")
            lines.append("            endcase")
            lines.append("        end")
            lines.append("    end")
        else:
            if to_rm_ports:
                lines.append("    // Update input registers from queue")
                lines.append("    always @(posedge clk or negedge rst_n) begin")
                lines.append("        if (!rst_n) begin")
                for port in to_rm_ports:
                    lines.append(f"            {port.name}_reg <= 0;")
                lines.append("        end else if (from_static_valid) begin")
                offset = 0
                for port in to_rm_ports:
                    if port.width == 1:
                        lines.append(f"            {port.name}_reg <= from_static_data[{offset}];")
                    else:
                        lines.append(f"            {port.name}_reg <= from_static_data[{offset + port.width - 1}:{offset}];")
                    offset += port.width
                lines.append("        end")
                lines.append("    end")

        lines.append("")
        lines.append("endmodule")

        output_path = self.build_dir / f"{wrapper_module_name}.sv"
        output_path.write_text("\n".join(lines))
        logger.info(f"Generated RM-side wrapper: {output_path}")
        return output_path

    def generate_both(
        self,
        boundary: PartitionBoundary,
        rm_sources: List[str] = None,
        queue_prefix: str = None
    ) -> tuple:
        """
        Generate both static-side bridge and RM-side wrapper.

        Returns
        -------
        tuple
            (static_bridge_path, rm_wrapper_path)
        """
        static_path = self.generate_static_side_bridge(boundary, queue_prefix)
        rm_path = self.generate_rm_side_wrapper(boundary, rm_sources or [], queue_prefix)
        return static_path, rm_path
