// RM-side DPI wrapper for wide64_rm
// Partition: rp_wide64
// Generated by partial_reconfiguration DPI bridge generator

`timescale 1ns/1ps

module wide64_rm_dpi_wrapper (
    input wire clk
);

    import "DPI-C" function longint dpi_rm_rp_wide64_wide_in_recv_data();
    import "DPI-C" function int dpi_rm_rp_wide64_wide_in_recv_valid();
    import "DPI-C" function longint dpi_rm_rp_wide64_full64_in_recv_data();
    import "DPI-C" function int dpi_rm_rp_wide64_full64_in_recv_valid();
    import "DPI-C" function void dpi_rm_rp_wide64_wide_out_send(input longint data);
    import "DPI-C" function void dpi_rm_rp_wide64_full64_out_send(input longint data);

    reg [47:0] wide_in /* verilator public */;
    reg [63:0] full64_in /* verilator public */;
    wire [47:0] wide_out /* verilator public */;
    wire [63:0] full64_out /* verilator public */;

    // Instantiate the real RM: wide64_rm
    wide64_rm u_rm (
        .clk(clk),
        .wide_in(wide_in),
        .full64_in(full64_in),
        .wide_out(wide_out),
        .full64_out(full64_out)
    );

    // Update inputs from DPI channels (from static region)
    always @(posedge clk) begin
        if (dpi_rm_rp_wide64_wide_in_recv_valid())
            wide_in <= dpi_rm_rp_wide64_wide_in_recv_data()[47:0];
        if (dpi_rm_rp_wide64_full64_in_recv_valid())
            full64_in <= dpi_rm_rp_wide64_full64_in_recv_data();
    end

    // Send outputs to static region via DPI channels
    always @(posedge clk) begin
        dpi_rm_rp_wide64_wide_out_send(longint'({16'd0, wide_out}));
        dpi_rm_rp_wide64_full64_out_send(full64_out);
    end

endmodule