// RM-side DPI wrapper for weird_rm
// Partition: rp_dummy
// Generated by partial_reconfiguration DPI bridge generator

`timescale 1ns/1ps

module weird_rm_dpi_wrapper (
    input wire clk
);

    import "DPI-C" function void dpi_rm_rp_dummy_data_out_send(input int data);

    wire [31:0] data_out /* verilator public */;

    // Instantiate the real RM: weird_rm
    weird_rm u_rm (
        .sys_input(clk),
        .data_out(data_out)
    );

    // Send outputs to static region via DPI channels
    always @(posedge clk) begin
        dpi_rm_rp_dummy_data_out_send(data_out);
    end

endmodule